language: php
before_script:
- composer install --dev --no-interaction
- cd test/unit
script:
- ../../vendor/bin/phpunit . --bootstrap bootstrap.php --filter test* --coverage-clover=coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
php:
- 5.6
- 7.0